apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClassName | default .Release.Name }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- range .Values.secrets }}
      - objectName: "{{ .objectName }}"
        {{- if .objectAlias }}
        objectAlias: "{{ .objectAlias }}"
        {{- end }}
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: "{{ .path }}"
            objectAlias: "{{ .objectAlias }}"
          {{- end }}
        {{- end }}
      {{- end }}
  secretObjects:
    - secretName: {{ .Release.Name }}-secret
      type: Opaque
      data:
      {{- range .Values.secrets }}
        {{- if .objectAlias }}
        - key: "{{ .objectAlias }}"
          objectName: "{{ .objectAlias }}"
        {{- end }}
        {{- if .jmesPath }}
          {{- range .jmesPath }}
        - key: "{{ .objectAlias }}"
          objectName: "{{ .objectAlias }}"
          {{- end }}
        {{- end }}
      {{- end }}
